# Generated by Django 6.1.1 on 2026-09-10 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('plug_type', models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('CCS', 'CCS'), ('CHAdeMO', 'CHAdeMO')], max_length=20)),
                ('power_output', models.DecimalField(decimal_places=1, help_text='Power in kW', max_digits=5)),
                ('price_per_hour', models.DecimalField(decimal_places=2, help_text='Price in ₹', max_digits=6)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_stations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
