# Generated by Django 6.0.2 on 2026-09-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Host', 'Host (Charger Owner)'), ('Driver', 'Driver'), ('Admin', 'Admin (Platform Manager)')], default='Driver', max_length=10),
        ),
    ]
